import 'package:flutter/material.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'package:flutter/src/widgets/placeholder.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';
import 'package:sprint/res/res.dart';
import 'package:sprint/widgets/app_header.dart';
import 'package:sprint/widgets/app_text.dart';

class DieuKhoanChinhSach extends StatefulWidget {
  const DieuKhoanChinhSach({super.key});

  @override
  State<DieuKhoanChinhSach> createState() => _DieuKhoanChinhSachState();
}

class _DieuKhoanChinhSachState extends State<DieuKhoanChinhSach> {
  @override
  Widget build(BuildContext context) {
    final viewPadding = MediaQuery.of(context).viewPadding;

    return Scaffold(
      backgroundColor: const Color(0xFFF7FAFE),
      body: Column(
        children: [
          AppHeader(title: 'Điều khoản chính sách'.tr),
          Expanded(
            child: SingleChildScrollView(
                padding: EdgeInsets.only(
                    top: 16.sp,
                    left: 16.sp,
                    right: 16.sp,
                    bottom: viewPadding.bottom + 30.sp),
                child: Column(
                  children: [
                    AppText(
                      "Điều chỉnh lần cuối: ngày 20 tháng 5 năm 2023\n\n"
                          "Thông Báo Bảo Mật này và (các) Phụ lục kèm theo (“Thông Báo Bảo Mật”) mô tả cách thức Công Ty Alo ship 99  tổ chức, pháp nhân chịu chung sự kiểm soát (sau đây gọi chung là “Alo ship 99”, “chúng tôi”, “của chúng tôi”) thu thập, sử dụng, xử lý và tiết lộ Dữ Liệu Cá Nhân của bạn thông qua việc sử dụng Ứng Dụng Di động (sau đây được gọi chung là “Ứng Dụng”  sản phẩm, tính năng và các dịch vụ khác, được cung cấp bởi Alo ship 99 trên toàn cầu (gọi chung là “Dịch Vụ”).\n\n"
                          "Thông Báo Bảo Mật này áp dụng cho tất cả các khách hàng, hành khách, đại lý, nhà cung cấp, đối tác (như lái xe, các đối tác giao nhận và đối tác thương nhân), nhà thầu và các nhà cung cấp dịch vụ (sau đây được gọi chung là “bạn”, “của bạn”)\n\n"
                          "“Dữ Liệu Cá Nhân” là bất kỳ thông tin nào có thể được sử dụng để nhận dạng bạn hoặc dựa vào đó mà bạn được xác định. Điều này bao gồm nhưng không giới hạn ở tên, quốc tịch, số điện thoại, chi tiết thẻ tín dụng và ngân hàng, sở thích cá nhân, địa chỉ email, hình ảnh của bạn, số nhận dạng do chính phủ cấp, dữ liệu sinh trắc học, chủng tộc, ngày sinh, tình trạng hôn nhân, tôn giáo, thông tin sức khỏe, xe và thông tin bảo hiểm, thông tin việc làm và thông tin tài chính.\n\n"
                          "Chúng tôi thu thập, sử dụng, tiết lộ, xử lý Dữ Liệu Cá Nhân theo quy định tại Thông Báo Bảo Mật mà bạn đã chấp thuận hoặc theo quy định của pháp luật hiện hành, chẳng hạn như khi:\n\n"
                          "•	chúng tôi được yêu cầu cho mục đích tuân thủ các quy định pháp luật;\n\n"
                          "•	chúng tôi được yêu cầu cho mục đích giao kết hoặc thực hiện hợp đồng với bạn; và/hoặc\n\n"
                          "•	cho lợi ích hợp pháp của chúng tôi và bất kỳ người nào khác, bao gồm nhưng không giới hạn bởi các mục đích được quy định tại Thông Báo Bảo Mật này.\n\n"
                          "I. VIỆC THU THẬP DỮ LIỆU CÁ NHÂN\n\n"
                          "Chúng tôi thu thập (và có thể kết hợp) Dữ Liệu Cá Nhân về bạn theo cách được liệt kê dưới đây:\n\n"
                          "Bạn cung cấp Dữ Liệu Cá Nhân cho chúng tôi\n\n"
                          "Chúng tôi thu thập Dữ Liệu Cá Nhân của bạn khi bạn cung cấp cho chúng tôi. Ví dụ, khi bạn:\n\n"
                          "•	hoàn tất hồ sơ người dùng hoặc các biểu mẫu đăng ký (như tên của bạn, thông tin liên lạc và thông tin nhận dạng khác khi cần thiết);\n\n"
                          "•	cung cấp thông tin để đánh giá việc bạn có đủ điều kiện để cung cấp dịch vụ như là một đối tác tài xế hoặc đối tác vận chuyển của Alo ship 99 (như thông tin giấy phép lái xe, thông tin phương tiện và kết quả kiểm tra lý lịch);\n\n"
                          "•	tương tác với các trang truyền thông xã hội của chúng tôi (như số ID tài khoản truyền thông xã hội của bạn, ảnh đại diện và bất kì dữ liệu công khai nào khác);\n\n"
                          "•	tham gia các cuộc thi hoặc sự kiện do chúng tôi tổ chức (như các tranh ảnh, âm thanh hoặc video mà bạn có thể gửi, có thể bao gồm hình ảnh của chính bạn);\n\n"
                          "•	xác minh danh tính của bạn thông qua các phương tiện khác nhau (như đăng nhập phương tiện truyền thông xã hội, gửi hình ảnh selfie hoặc thông tin thẻ thanh toán được xác minh một cách độc lập);\n\n"
                          "•	điền thông tin nhân khẩu trong các cuộc khảo sát (như tuổi, giới tính của bạn, và thông tin khác mà bạn có thể tình nguyện như tình trạng hôn nhân, nghề nghiệp và thông tin thu nhập của bạn); và\n\n"
                          "•	đồng ý sử dụng chuyến xe có các tính năng ghi âm và/ hoặc quay video trên xe.\n\n"
                          "Khi Dịch Vụ của chúng tôi được sử dụng\n\n"
                          "Dữ Liệu Cá Nhân có thể được thu thập thông qua hoạt động bình thường hoặc qua việc sử dụng Ứng Dụng, s, Dịch Vụ. Một số ví dụ như:\n\n"
                          "•	thông tin vị trí của bạn;\n\n"
                          "•	phản hồi, xếp hạng và khen ngợi;\n\n"
                          "•	thông tin giao dịch (như phương thức thanh toán);\n\n"
                          "•	thông tin về cách bạn tương tác với Ứng dụng, Dịch vụ của chúng tôi (như các tính năng được sử dụng và nội dung được xem);\n\n"
                          "•	thông tin thiết bị (như thông số phần cứng và số sê-ri, các địa chỉ IP, tên tệp, ứng dụng, vị trí GPS, số IMEI và phiên bản và nhận dạng quảng cáo, hoặc bất kỳ thông tin nào có thể chỉ dẫn về những thay đổi của thiết bị hoặc ứng dụng);\n\n"
                          "•	dữ liệu viễn thông (chẳng hạn như dữ liệu về tốc độ, gia tốc và dữ liệu phanh của bạn);\n\n"
                          "•\n\n"
                          "o	Chúng tôi làm việc với các đối tác để lắp đặt các thiết bị viễn thông trong những phương tiện cho thuê nhằm các mục đích sau:\n\n"
                          "•\n\n"
                          "o\n\n"
                          "	để đảm bảo các phương tiện được bảo dưỡng một các thích hợp và kịp thời;\n\n"
                          "	để duy trì sự an toàn, đảm bảo và toàn vẹn của các Dịch Vụ của chúng tôi;\n\n"
                          "	để cải thiện và nâng cao chất lượng Dịch Vụ của chúng tôi; và\n\n"
                          "	để theo dõi nội bộ phương tiện, mục đích phân tích và các mục đích hành chính khác.\n\n"
                          "•\n\n"
                          "o	Những đối tác sở hữu và chia sẻ dữ liệu viễn thông với chúng tôi:\n\n"
                          "	các đối tác của chúng tôi cũng có nghĩa vụ theo hợp đồng để bảo vệ các dữ liệu này.\n\n"
                          "•	dữ liệu cá nhân bạn nhập trong tin nhắn khi bạn sử dụng tính năng giao tiếp trong ứng dụng của chúng tôi; và\n\n"
                          "•	dữ liệu cá nhân có thể được ghi lại thông qua tương tác của bạn với chúng tôi, các đại lý của chúng tôi, ghi âm trên xe và / hoặc video ghi lại trong cuốc xe (như hình ảnh hoặc giọng nói của bạn hoặc cả hai, và siêu dữ liệu liên quan của nó).\n\n"
                          "•\n\n"
                          "o	các ứng dụng và thiết bị trên xe của chúng tôi:\n\n"
                          "•\n\n"
                          "o\n\n"
                          "	chúng tôi có thể lắp đặt các ứng dụng và thiết bị trên xe để thúc đẩy sự an toàn và đảm bảo đôi với các đối tác tài xế, đối tác nhà giao nhận và khách hàng của chúng tôi.\n\n"
                          "	dữ Liệu Cá Nhân của bạn có thể được ghi lại trong các dữ liệu ghi âm hoặc ghi hình. Khi việc ghi âm hoặc ghi hình được thực hiện, các dữ liệu ghi này được thu thập, xử lý, sử dụng và lưu trữ theo các quy định tại Thông Báo Bảo Mật này và các quy định pháp luật hiện hành.\n\n"
                          "Xin hãy lưu ý rằng, một vài đối tác của Alo ship 99 có thể lắp đặt các ứng dụng và thiết bị trên xe của họ cho những mục đích cá nhân của họ, điều này có thể dẫn đến việc Dữ Liệu Cá Nhân của bạn có thể được lưu lại bởi họ trong quá trình sử dụng Dịch Vụ của chúng tôi. Việc này không được xác nhận hay bị cấm bởi Alo ship 99 và việc thu thập, sử dụng và tiết lộ các Dữ Liệu Cá Nhân này là trách nhiệm thuộc về các đối tác có liên quan. Vui lòng kiểm tra với các đối tác có liên quan nếu bạn có bất kỳ thắc mắc nào về việc sử dụng các thiết bị ghi hình cá nhân trong phương tiện của họ.\n\n"
                          "Từ các nguồn khác\n\n"
                          "Chúng tôi có thể thu thập Dữ Liệu Cá Nhân, bao gồm nhưng không giới hạn ở tên của bạn, thông tin liên hệ và thông tin nhận dạng khác, từ các nguồn khác khi cần thiết. Những nguồn này bao gồm:\n\n"
                          "•	từ các chương trình giới thiệu;\n\n"
                          "•	từ các đối tác kinh doanh của chúng tôi, chẳng hạn như các đối tác vận tải, nhà cung cấp dịch vụ thanh toán, đối tác dịch vụ gọi xe và đối tác vận chuyển;\n\n"
                          "•	nhà cung cấp bảo hiểm và tài chính;\n\n"
                          "•	trung tâm tín dụng và các đại lý báo cáo tín dụng khác;\n\n"
                          "•	nguồn dữ liệu công khai có sẵn hoặc nguồn dữ liệu chính phủ;\n\n"
                          "•	khi người dùng của chúng tôi thêm bạn làm người liên lạc khẩn cấp;\n\n"
                          "•	khi người dùng của chúng tôi thêm bạn như là người nhận hoặc người thụ hưởng của việc sử dụng bất kỳ Dịch Vụ nào của chúng tôi;\n\n"
                          "•	khi bạn sử dụng trò chuyện trong Ứng Dụng; và\n\n"
                          "•	nhà cung cấp hoặc đối tác dịch vụ tiếp thị.\n\n"
                          "Dữ Liệu Cá Nhân nhạy cảm\n\n"
                          "Một số Dữ Liệu Cá Nhân mà chúng tôi thu thập là nhạy cảm theo đặc tính tự nhiên. Điều này bao gồm Dữ Liệu Cá Nhân liên quan đến chủng tộc của bạn, thông tin số CMND/ số thẻ căn cước công dân, niềm tin tôn giáo, thông tin lý lịch (bao gồm hồ sơ tài chính và lý lịch tư pháp, khi được phép hợp pháp), dữ liệu sức khỏe, khuyết tật, tình trạng hôn nhân và dữ liệu sinh trắc học, nếu phù hợp. Chúng tôi chỉ thu thập thông tin này với sự đồng thuận của bạn và/hoặc tuân thủ nghiêm ngặt các luật áp dụng hiện hành. Trong trường hợp bạn được yêu cầu cung cấp bất kỳ tài liệu hoặc thông tin nào cho chúng tôi cho bất kỳ Mục Đích nào mà có thể chứa Dữ Liệu Cá Nhân nhạy cảm đó (không bắt buộc đối với Mục Đích đó), bạn đồng ý loại bỏ đi Dữ Liệu Cá Nhân nhạy cảm đó trước khi cung cấp tài liệu hoặc thông tin đó cho chúng tôi.\n\n"
                          "Khi bạn cung cấp Dữ Liệu Cá Nhân của một người khác cho chúng tôi\n\n"
                          "Trong một số trường hợp, bạn có thể cung cấp Dữ Liệu Cá Nhân của các cá nhân khác (như vợ/ chồng, thành viên gia đình hoặc bạn bè) cho chúng tôi. Ví dụ, bạn có thể thêm họ như người liên hệ khẩn cấp của bạn, khi bạn sử dụng trò chuyện trong Ứng Dụng hoặc khi bạn thêm họ như là người nhận hoặc người thụ hưởng của bất kỳ việc sử dụng các Dịch Vụ của chúng tôi. Nếu bạn cung cấp cho chúng tôi Dữ Liệu Cá Nhân của họ, bạn cam đoan và bảo đảm rằng bạn đã có được sự chấp thuận của họ để Dữ Liệu Cá Nhân của họ được thu thập, sử dụng và tiết lộ như quy định trong Thông Báo Bảo Mật này.\n\n"
                          "Dữ Liệu Cá Nhân của trẻ vị thành niên\n\n"
                          "Là cha mẹ hoặc người giám hộ hợp pháp, vui lòng không cho phép trẻ vị thành niên đặt dưới sự chăm sóc của bạn gởi Dữ Liệu Cá Nhân cho Alo ship 99. Trong trường hợp Dữ Liệu Cá Nhân của trẻ vị thành niên được tiết lộ cho Alo ship 99, bạn theo đó chấp thuận việc xử lý Dữ Liệu Cá Nhân của trẻ vị thành niên, chấp nhận và đồng ý chịu ràng buộc theo Thông Báo Bảo Mật này và chịu trách nhiệm đối với các hành động của trẻ vị thành niên do mình giám hộ hợp pháp.\n\n"
                          "II.    VIỆC SỬ DỤNG DỮ LIỆU CÁ NHÂN\n\n"
                          "Alo ship 99 có thể sử dụng Dữ Liệu Cá Nhân của bạn cho các mục đích được liệt kê sau đây (“Mục Đích”). Ngoài ra, nếu bạn sử dụng Alo ship 99 ở những mức độ khác nhau (ví dụ, nếu bạn sử dụng nhiều Dịch Vụ của Alo ship 99, hoặc nếu bạn vừa là đối tác tài xế/ đối tác giao nhận và là một khách hàng), chúng tôi có thể liên kết Dữ Liệu Cá Nhân của bạn đã được thu thập thông qua các mức độ khác nhau đó để tạo điều kiện cho bạn sử dụng Dịch Vụ của chúng tôi và cho các Mục Đích khác được mô tả dưới đây:\n\n"
                          "Cung cấp dịch vụ và các tính năng\n\n"
                          "Dữ Liệu Cá Nhân của bạn sẽ được sử dụng để cung cấp, cá nhân hóa, duy trì và cải thiện Ứng Dụng, s và Dịch Vụ của chúng tôi. Điều này bao gồm sử dụng Dữ Liệu Cá Nhân của bạn để:\n\n"
                          "•	tương tác để cung cấp cho bạn Dịch Vụ xuyên suốt các lĩnh vực kinh doanh khác nhau của chúng tôi;\n\n"
                          "•	tạo mới, quản trị và cập nhật tài khoản của bạn;\n\n"
                          "•	xử lý, quản lý hoặc xác minh điều kiện thực hiện Dịch Vụ, các ưu đãi, phần thưởng và đăng ký thuê bao với Alo ship 99;\n\n"
                          "•	tiến hành kiểm tra thẩm định và đánh giá/ phân tích rủi ro;\n\n"
                          "•	xác minh danh tính và tuổi của bạn (khi cần thiết);\n\n"
                          "•	xác nhận chuyến xe của bạn và thực hiện các khoản thanh toán;\n\n"
                          "•	đề xuất, có được, cung cấp, tạo điều kiện hoặc duy trì các giải pháp bảo hiểm hoặc tài chính;\n\n"
                          "•	theo dõi lộ trình chuyến đi của bạn và phát hiện các sự thay đổi chuyến đi bất thường;\n\n"
                          "•	cá nhân hóa việc trải nghiệm Ứng Dụng của bạn (chẳng hạn như đề xuất các sản phẩm, dịch vụ có thể liên quan đến bạn, xác định sở thích của bạn hoặc cá nhân hóa trải nghiệm của bạn với Alo ship 99);\n\n"
                          "•	làm cho trải nghiệm của bạn trở nên liền mạch hơn, như tự động điền thông tin đăng ký của bạn (như tên hoặc số điện thoại của bạn) từ Dịch Vụ này sang Dịch Vụ khác hoặc khi bạn tham gia vào các cuộc khảo sát của chúng tôi;\n\n"
                          "•	thực hiện các hoạt động nội bộ cần thiết để cung cấp Dịch Vụ, bao gồm khắc phục các lỗi phần mềm và sự cố vận hành, tiến hành phân tích dữ liệu, thử nghiệm và nghiên cứu, giám sát và phân tích xu hướng sử dụng và hoạt động;\n\n"
                          "•	bảo vệ tính bảo mật hoặc tính toàn vẹn của Dịch Vụ và mọi phương tiện hoặc thiết bị được sử dụng để cung cấp Dịch Vụ;\n\n"
                          "•	cho phép liên lạc giữa những người dùng của chúng tôi;\n\n"
                          "•	mời bạn tham gia các khảo sát và nghiên cứu của chúng tôi;\n\n"
                          "•	cho phép các đối tác của chúng tôi quản lý và phân bổ nguồn lực; và\n\n"
                          "•	để thực hiện các dịch vụ cho bạn với tư cách là một Bên Xử lý Dữ liệu, theo như bạn đã đồng thuận với Bên Kiểm soát Dữ liệu (ví dụ tổ chức bạn đã mua hàng hóa hoặc dịch vụ từ đó, và Alo ship 99 đang cung cấp những dịch vụ đó thay mặt cho ai) để các dịch vụ đó được triển khai.\n\n"
                          "An toàn và bảo mật\n\n"
                          "Chúng tôi sử dụng dữ liệu của bạn để đảm bảo an toàn và an ninh cho các Dịch Vụ của chúng tôi và cho tất cả người dùng. Điều này bao gồm:\n\n"
                          "•	sàng lọc tài xế và đối tác giao hàng trước khi cho phép họ sử dụng Dịch Vụ của chúng tôi;\n\n"
                          "•	xác định hành vi lái xe không an toàn như tốc độ nhanh, phanh gấp và tăng tốc và cung cấp phản hồi cá nhân cho các đối tác lái xe;\n\n"
                          "•	xác minh danh tính của bạn khi bạn đăng nhập vào Alo ship 99;\n\n"
                          "•	sử dụng thiết bị, vị trí, hồ sơ, cách sử dụng và Dữ Liệu Cá Nhân khác để ngăn chặn, phát hiện và chống lại các hoạt động gian lận hoặc không an toàn;\n\n"
                          "•	chia sẻ vị trí và thông tin chi tiết của đối tác tài xế và hành khách khi nút khẩn cấp hoặc tính năng “chia sẻ chuyến đi của tôi” được kích hoạt; và\n\n"
                          "•	giám sát việc tuân thủ các điều khoản và điều kiện, các chính sách của chúng tôi;\n\n"
                          "Hỗ trợ khách hàng\n\n"
                          "Chúng tôi sử dụng Dữ Liệu Cá Nhân để giải quyết các vấn đề hỗ trợ khách hàng. Ví dụ, chúng tôi có thể:\n\n"
                          "•	điều tra và chỉ ra các vấn đề cần quan tâm;\n\n"
                          "•	theo dõi và cải thiện cách phản hồi từ bộ phận hỗ trợ khách hàng của chúng tôi;\n\n"
                          "•	trả lời các câu hỏi, ý kiến và phản hồi; và\n\n"
                          "•	thông báo cho bạn về các bước thực hiện để giải quyết các vấn đề hỗ trợ khách hàng.\n\n"
                          "Nghiên cứu phát triển và bảo mật\n\n"
                          "Chúng tôi có thể sử dụng Dữ Liệu Cá Nhân mà chúng tôi thu thập để thử nghiệm, nghiên cứu, phân tích và phát triển sản phẩm. Điều này cho phép chúng tôi hiểu và phân tích nhu cầu và sở thích của bạn, bảo vệ dữ liệu cá nhân của bạn, cải thiện và tăng cường an toàn và bảo mật cho các Dịch Vụ của chúng tôi, phát triển các tính năng, sản phẩm và dịch vụ mới và tạo điều kiện phát triển các giải pháp tài chính và bảo hiểm.\n\n"
                          "Mục đích pháp lý\n\n"
                          "Chúng tôi có thể sử dụng Dữ Liệu Cá Nhân mà chúng tôi thu thập cho các mục đích pháp lý, chẳng hạn như để điều tra và giải quyết khiếu nại hoặc tranh chấp, phát hiện/ ngăn chặn/ khởi tố tội phạm hoặc khi được cho phép hoặc yêu cầu theo pháp luật áp dụng.Chúng tôi cũng có thể sử dụng Dữ Liệu Cá Nhân của bạn khi chúng tôi được yêu cầu, được tư vấn, đề nghị, đòi hỏi hoặc thỉnh cầu làm như vậy bởi các cố vấn pháp lý của chúng tôi hoặc bất kỳ quy định pháp luật, văn bản dưới luật, thuộc về chính phủ hay các cơ quan có thẩm quyền tại địa phương hoặc nước ngoài.\n\n"
                          "Ví dụ, chúng tôi có thể sử dụng Dữ Liệu Cá Nhân của bạn để:\n\n"
                          "•	tuân thủ các lệnh của tòa án hoặc các yêu cầu pháp lý, thuộc về chính phủ hoặc quy định khác;\n\n"
                          "•	thực thi Điều Khoản Dịch Vụ của chúng tôi hoặc các thỏa thuận khác; và\n\n"
                          "•	bảo vệ quyền hoặc tài sản của chúng tôi trong trường hợp khiếu nại hoặc tranh chấp.\n\n"
                          "Tiếp Thị và Quảng Bá\n\n"
                          "Chúng tôi có thể sử dụng Dữ Liệu Cá Nhân của bạn để gửi đến bạn các thông tin tiếp thị liên quan đến các sản phẩm hoặc dịch vụ được cá nhân hóa (điều mà bạn có thể cảm thấy thú vị hoặc có liên quan đến mình dựa trên thông tin tài khoản của bạn) hoặc  của các đối tác nhà tài trợ của Alo ship 99, và các nhà quảng cáo sản phẩm, dịch vụ, sự kiện hoặc chương trình khuyến mại. Ví dụ, chúng tôi có thể:\n\n"
                          "•	gửi cho bạn những ưu đãi đặc biệt , điều mà bạn có thể cảm thấy thú vị hoặc có liên quan đến mình qua các đề xuất dịch vụ của Alo ship 99;\n\n"
                          "•	gửi cho bạn thông báo, bản tin, cập nhật, thư điện tử, tài liệu quảng cáo, đặc quyền, lời chúc mừng lễ hội; và\n\n"
                          "•	thông báo, mời và quản lý sự tham gia của bạn vào các sự kiện hoặc hoạt động của chúng tôi;\n\n"
                          "Chúng tôi có thể liên lạc tiếp thị như vậy với bạn qua nhiều phương tiện khác nhau, nếu phù hợp, bao gồm tin nhắn, các ứng dụng trò chuyện (ví dụ, Whatsapp, Telegram, LINE, Viber, WeChat, Zalo), thông báo nhanh, cuộc gọi và qua email.\n\n"
                          "Nếu bạn muốn hủy đăng ký về việc nhận các thông tin tiếp thị này, vui lòng nhấp vào liên kết hủy đăng ký trong email hoặc tin nhắn có liên quan. Ngoài ra, bạn cũng có thể cập nhật tùy chọn của mình trong phần cài đặt Ứng Dụng. Xin lưu ý rằng, khi bạn đã hủy đăng ký khỏi các chương trình tiếp thị hoặc khuyến mãi, Alo ship 99 vẫn có thể sẽ gửi cho bạn tin nhắn liên quan đến Dịch Vụ (chẳng hạn như thông tin về các giao dịch, phần thưởng… của bạn).\n\n"
                          "Nội dung được công khai bởi người dùng\n\n"
                          "Nếu bạn công khai một số nội dung (chẳng hạn như đánh giá hoặc bình luận) trên nền tảng của Alo ship 99, nó sẽ được xem một cách công khai cùng với Dữ Liệu Cá Nhân của bạn (ví dụ như tên tài khoản, hình ảnh đã tải lên và các thông tin khác mà bạn đã để nó trong nội dung của mình). Để có nhiều thông tin hơn, hãy xem Hướng Dẫn về các Đánh Giá Do người dùng khởi tạo của chúng tôi.\n\n"
                          "III.    Tiết Lộ Dữ Liệu Cá Nhân\n\n"
                          "Chúng tôi cần chia sẻ Dữ Liệu Cá Nhân với các bên khác nhau cho các Mục Đích. Các bên này bao gồm:\n\n"
                          "Người dùng khác\n\n"
                          "Ví dụ:\n\n"
                          "•	nếu bạn là hành khách, chúng tôi có thể chia sẻ tên tài khoản người dùng, địa điểm đón và trả khách của bạn với đối tác tài xế của chúng tôi để thực hiện yêu cầu Dịch Vụ của bạn.\n\n"
                          "•	nếu bạn là đối tác tài xế, chúng tôi có thể chia sẻ Dữ Liệu Cá Nhân của bạn với hành khách của bạn bao gồm tên và ảnh của bạn; thông tin xe của bạn, loại xe, biển số, vị trí và mức đánh giá trung bình;\n\n"
                          "•	nếu bạn là đối tác vận chuyển, chúng tôi có thể chia sẻ Dữ Liệu Cá Nhân của bạn với đối tác thương mại và người sử dụng bạn đã chọn, bao gồm tên và hình ảnh; thông tin xe của bạn, loại xe, vị trí và mức đánh giá trung bình;\n\n"
                          "•	nếu bạn đang sử dụng Dịch Vụ Alo ship 99Express, chúng tôi có thể chia sẻ Dữ Liệu Cá Nhân của bạn với bên nhận gói hàng của bạn, và ngược lại, cũng như đối với các đối tác vận chuyển phụ trách thực hiện yêu cầu dịch vụ của bạn; và\n\n"
                          "•	nếu bạn sử dụng dịch vụ trò chuyện trong Ứng Dụng, chúng tôi có thể chia sẻ số điện thoại của bạn và tên đăng ký Alo ship 99 của bạn với các bên khác vào cuộc trò chuyện của bạn.\n\n"
                          "Với bên thứ ba\n\n"
                          "Với các bên thứ ba liên quan đến việc sử dụng Dịch Vụ Alo ship 99 của bạn\n\n"
                          "Ví dụ:\n\n"
                          "•	Nếu bạn là hành khách của các đối tác tài xế, chúng tôi có thể chia sẻ vị trí phương tiện và tên của tài xế và/ hoặc tên hành khách với các bên thứ ba khi hành khách sử dụng tính năng “Chia sẻ Chuyến đi Của tôi” hoặc kích hoạt Nút Khẩn cấp.\n\n"
                          "•	Nếu bạn là đối tác tài xế, chúng tôi có thể tiết lộ biển số phương tiện hoặc các thông tin cá nhân khác cho công ty bảo hiểm và/hoặc đến các hành khách cho mục đích nộp các khiếu nại bảo hiểm.\n\n"
                          "Với chủ sở hữu tài khoản Alo ship 99 mà bạn có thể sử dụng\n\n"
                          "Ví dụ, người sử dụng lao động của bạn có thể nhận dữ liệu chuyến (được đánh dấu là chuyến đi từ doanh nghiệp) khi bạn sử dụng tài khoản Alo ship 99 for Business của người sử dụng lao động.\n\n"
                          "Với các công ty con và chi nhánh\n\n"
                          "Chúng tôi chia sẻ Dữ Liệu Cá Nhân với các công ty con, công ty liên kết, các đơn vị và chi nhánh được kiểm soát chung. Các công ty ở Alo ship 99 chia sẻ với nhau về nguồn lực, chẳng hạn như hạ tầng và công nghệ, để cung cấp đến bạn một sự đồng bộ, liên quan và đảm bảo trải nghiệm khi bạn sử dụng Dịch Vụ, và cho Mục Đích được quy định trong Thông Báo Bảo Mật này.\n\n"
                          "Ví dụ, chúng tôi làm điều này để trải nghiệm của bạn được liền mạch hơn, chẳng hạn như tự động hoàn thành thông tin đăng ký của bạn, từ việc bạn đã sử dụng một Dịch Vụ nào đó của Alo ship 99 cho việc bạn đăng ký đối với một Dịch Vụ mới của Alo ship 99.\n\n"
                          "Với các nhà cung cấp dịch vụ và đối tác kinh doanh của Alo ship 99\n\n"
                          "Chúng tôi có thể cung cấp Dữ Liệu Cá Nhân cho các nhà cung cấp, chuyên gia tư vấn, đối tác tiếp thị, công ty nghiên cứu và nhà cung cấp dịch vụ hoặc đối tác kinh doanh khác. Điều nay bao gồm:\n\n"
                          "•	bộ phận xử lý thanh toán và bộ phận hỗ trợ;\n\n"
                          "•	bộ phận thu hồi nợ;\n\n"
                          "•	trung tâm tín dụng và các đại lý báo cáo tín dụng khác;\n\n"
                          "•	kiểm tra lý lịch và các nhà cung cấp dịch vụ chống rửa tiền;\n\n"
                          "•	nhà cung cấp lưu trữ đám mây;\n\n"
                          "•	đối tác quảng cáo và tiếp thị và nhà cung cấp nền tảng;\n\n"
                          "•	nhà cung cấp phân tích dữ liệu;\n\n"
                          "•	các đối tác nghiên cứu, bao gồm cả những người thực hiện khảo sát hoặc dự án nghiên cứu hợp tác với Alo ship 99 hoặc thay mặt Alo ship 99;\n\n"
                          "•	các đối tác trung tâm giáo dục và đào tạo;\n\n"
                          "•	các đối tác thương nhân và vận tải;\n\n"
                          "•	đối tác bảo hiểm và tài chính;\n\n"
                          "•	các trung gian bên thứ ba có liên quan đến khoản đầu tư được quản lý của các quỹ, như bên môi giới, bên quản lý tài sản và bên giám sát;\n\n"
                          "•	nhà cung cấp dịch vụ thực hiện dịch vụ xác minh danh tính; và\n\n"
                          "•	đối tác giải pháp xe, nhà cung cấp hoặc nhà cung cấp xe của bên thứ ba.\n\n"
                          "Ví dụ:\n\n"
                          "•	Nếu bạn yêu cầu một dịch vụ thông qua đối tác của Alo ship 99 hoặc sử dụng một ưu đãi được cung cấp bởi đối tác Alo ship 99, Alo ship 99 có thể chia sẻ Dữ Liệu Cá Nhân của bạn với đối tác đó của Alo ship 99.\n\n"
                          "•	Nếu bạn đã thuê một phương tiện từ một đối tác vận tải được đề xuất để lái cùng Alo ship 99, chúng tôi có thể chia sẻ thông tin liên quan (ví dụ, tình trạng tài khoản của bạn,  các ưu đãi/ hỗ trợ hiện đang áp dụng, thông kê chuyến xe của bạn) cho một nỗ lực hợp tác (ví dụ, để tạo ra các hỗ trợ/ lợi ích mới cho bạn hoặc để cải thiện nguồn cung đối tác tài xế)\n\n"
                          "Với các cố vấn pháp lý của chúng tôi và các cơ quan chính phủ\n\n"
                          "Chúng tôi có thể chia sẻ Dữ Liệu Cá Nhân của bạn với các cố vấn pháp lý, các quan chức thực thi pháp luật, cơ quan chính phủ và các bên thứ ba khác. Việc này có thể được thực hiện để hoàn thành mục đích pháp lý (đã đề cập ở trên), hoặc bất kì trường hợp nào sau đây:\n\n"
                          "•	khi điều này là cần thiết để phản ứng với một tình huống khẩn cấp đe doạ tính mạng, sức khoẻ hoặc sự an toàn của một thực thể; hoặc\n\n"
                          "•	khi điều này là cần thiết trong lợi ích công cộng (ví dụ: trong một cuộc khủng hoảng sức khỏe công cộng, cho mục đích truy dấu sự tiếp xúc và bảo vệ cộng đồng của chúng ta).\n\n"
                          "Chuyển giao kinh doanh\n\n"
                          "Chúng tôi có thể chia sẻ Dữ Liệu Cá Nhân của bạn với các bên khác, liên quan đến bất kỳ hoạt động hợp nhất, mua bán, sát nhập, hợp tác, tái cấu trúc, tài chính hoặc bất kỳ giao dịch kinh doanh nào khác. Dữ Liệu Cá Nhân của bạn, vẫn sẽ chịu trách nhiệm bởi chúng tôi theo các Thông Bảo Mật đã tồn tại từ trước mà bạn đã đồng ý.\n\n"
                          "IV.    VIỆC LƯU GIỮ DỮ LIỆU CÁ NHÂN\n\n"
                          "Chúng tôi lưu giữ Dữ Liệu Cá Nhân của bạn trong khoảng thời gian cần thiết để thực hiện các Mục đích được nêu trong Thông Báo Bảo Mật này, trừ khi pháp luật yêu cầu hoặc cho phép một khoảng thời gian lưu giữ lâu hơn. Khi Dữ Liệu Cá Nhân của bạn không còn cần thiết cho Dịch Vụ hoặc Mục Đích, hoặc chúng tôi không còn có mục đích kinh doanh hoặc pháp lý để giữ lại Dữ Liệu Cá Nhân của bạn, chúng tôi sẽ thực hiện các bước để xoá, tiêu huỷ, ẩn danh hoặc ngăn chặn việc truy cập hoặc sử dụng Dữ Liệu Cá Nhân cho bất kỳ mục đích nào ngoài việc tuân thủ theo Thông Báo Bảo Mật này, hoặc cho mục đích an toàn, bảo mật, phát hiện và phòng chống gian lận, phù hợp với các yêu cầu của luật áp dụng hiện hành.\n\n"
                          "V.    CHUYỂN GIAO QUỐC TẾ DỮ LIỆU CÁ NHÂN\n\n"
                          "Dữ Liệu Cá Nhân của bạn có thể được chuyển từ quốc gia, tiểu bang và thành phố (“Quốc Gia Sở Tại”), nơi bạn có mặt trong khi sử dụng Dịch Vụ của chúng tôi đến một quốc gia, tiểu bang và thành phố khác (“Quốc Gia Thay Thế”). Khi chúng tôi chuyển Dữ Liệu Cá Nhân của bạn từ Quốc gia Sở tại đến Quốc gia Thay thế, chúng tôi sẽ tuân thủ các nghĩa vụ pháp lý và quy định liên quan đến Dữ Liệu Cá Nhân của bạn, bao gồm có cơ sở hợp pháp để chuyển Dữ Liệu Cá Nhân và áp dụng các biện pháp bảo vệ phù hợp để đảm bảo đầy đủ mức độ bảo vệ Dữ Liệu Cá Nhân. Chúng tôi cũng sẽ đảm bảo rằng bên nhận ở Quốc gia Thay thế có nghĩa vụ bảo vệ Dữ Liệu Cá Nhân của bạn theo tiêu chuẩn bảo vệ tương đương với sự bảo vệ theo luật áp dụng hiện hành.\n\n"
                          "Cơ sở hợp pháp của chúng tôi sẽ là hoặc sự đồng thuận (ví dụ chúng tôi có thể yêu cầu sự đồng thuận của bạn để chuyển Dữ Liệu Cá Nhân của bạn từ Quốc Gia Sở Tại đến Quốc Gia Thay Thế vào thời điểm bạn cung cấp Dữ Liệu Cá Nhân) hoặc một trong những biện pháp bảo vệ được pháp luật cho phép.\n\n"
                          "VI.    COOKIES và quảng cáo trên các nền tảng bên thứ ba\n\n"
                          "Cookies\n\n"
                          "Alo ship 99 và các bên thứ ba mà chúng tôi hợp tác, có thể sẽ sử dụng cookies, web beacon, tags, scripts, các đối tượng chia sẻ dữ liệu như HTML5, công cụ định danh quảng cáo và các công nghệ tương tự (theo đây được gọi chung là “Cookies”) có liên quan đến việc sử dụng các s và Ứng Dụng của bạn, có thể liên tục hoặc chỉ được lưu trữ trong một phiên riêng lẻ trên trình duyệt hoặc thiết bị của bạn.\n\n"
                          "Cookies có thể chứa đựng các công cụ định danh độc nhất và trú tại, ngoài các nơi khác, máy tính hoặc thiết bị di động của bạn, trong email mà chúng tôi gửi cho bạn, và trên các trang web của chúng tôi. Cookies có thể được sử dụng cho những mục đích khác nhau chẳng hạn như:\n\n"
                          "•	Cung cấp những tính năng cơ bản và cần thiết cho việc sử dụng các s, Dịch Vụ và Ứng Dụng của chúng tôi;\n\n"
                          "•	Xác thực bạn, hoặc ghi nhớ các cài đặt và người dùng yêu tích của bạn;\n\n"
                          "•	Truyền đạt và đo lường tính hiệu quả của các chiến dịch quảng cáo, chẳng hạn bằng việc đo số lượt xem hoặc truy cập;\n\n"
                          "•	Phân tích lưu lượng truy cập trang web và xu hướng;\n\n"
                          "•	Truyền tải đến bạn các quảng cáo có liên quan trên các ứng dụng và trang web thuộc sở hữu của công ty khác (được sở hữu bởi chúng tôi hoặc các nhà quảng cáo khác);\n\n"
                          "•	Nâng cao giao diện và trải nghiệm người dùng bằng cách hiểu chung về hành vi trực tuyến và sở thích của người dùng tương tác với , Dịch Vụ, Ứng Dụng của chúng tôi.\n\n"
                          "Alo ship 99 có thể cho phép các bên thứ ba sử dụng Cookies trên s và Ứng Dụng để thu thập cùng loại Dữ Liệu Cá Nhân cho cùng mục đích mà Alo ship 99 tự làm. Các bên thứ ba có thể liên kết Dữ Liệu Cá Nhân họ thu thập với Dữ Liệu Cá Nhân khác mà họ có về bạn từ các nguồn khác. Chúng tôi không cần thiết có quyền truy cập hoặc kiểm soát Cookies họ sử dụng.\n\n"
                          "Tắt việc thu thập cookies trên các s của chúng tôi\n\n"
                          "Bạn có quyền để chọn tắt, chặn hoặc ngừng hoạt động cookies. Xin lưu ý rằng, mặc dù vậy, việc từ chối hoặc loại bỏ một số cookies có thể ảnh hưởng đến sự sẵn có, chức năng hoặc việc sử dụng s, Dịch Vụ, Ứng Dụng của chúng tôi\n\n"
                          "Bạn có thể điều chỉnh cài đặt trình duyệt internet để tắt, chặn hoặc ngừng hoạt động cookies, xóa lịch sử duyệt web hoặc xóa bộ nhớ cache khỏi trình duyệt internet của bạn.\n\n"
                          "Những cài đặt này có thể được chứa ở các phần về “Lịch sử”, “Tùy chọn”, “Cài đặt” hoặc “Riêng tư” trong trình duyệt internet của bạn hoặc bạn cũng có thể yêu cầu trợ giúp đến từ trình duyệt internet để có thêm thông tin.\n\n"
                          "Tắt hiển thị của các Quảng Cáo Mục Tiêu ở các nền tảng khác\n\n"
                          "Chúng tôi có thể tạo điều kiện cho việc hiển thị Quảng cáo Mục Tiêu trên các nền tảng khác, chẳng hạn như trên các nền tảng trực tuyến khác mà bạn có thể là người dùng.\n\n"
                          "Bạn có thể giới hạn việc chúng tôi sử dụng Dữ Liệu Cá Nhân của bạn để thay mặt các nhà quảng cáo của chúng tôi hiển thị các Quảng cáo Mục Tiêu, bằng cách điều chỉnh tùy chọn của bạn thông qua Ứng Dụng. Tùy thuộc vào loại điện thoại và phần mềm điều hành mà bạn đang sử dụng, bạn có thể được cấp tùy chọn để vô hiệu hóa việc sử dụng số nhận dạng di động của chúng tôi (chẳng hạn như IDFA của Apple hoặc GAID của Google) và khả năng theo dõi bạn trên các ứng dụng và trang web do các công ty khác sở hữu bằng cách điều chỉnh các cài đặt có sẵn trên thiết bị di động của bạn. Thông qua việc điều chỉnh cài đặt trên thiết bị của mình, bạn thường có thể đặt lại, xóa, giới hạn và/hoặc hạn chế việc sử dụng các nhận dạng di động đó.\n\n"
                          "Mặc dù chúng tôi sẽ không sử dụng Dữ Liệu Cá Nhân của bạn để hiển thị cho bạn những Quảng Cáo Mục Tiêu như vậy trên các nền tảng khác, bạn vẫn có thể thấy những quảng cáo chung xuất hiện có thể liên quan đến bạn. Điều này có thể là do chúng tôi đã hợp tác với các nhà quảng cáo/ nền tảng của bên thứ ba để hiển thị quảng cáo cho những người dùng có các thuộc tính hoặc nhân khẩu học cụ thể và những người này có thể thấy chúng có liên quan đến mình. Bạn có thể hạn chế việc nhìn thấy những quảng cáo này thông qua việc quản lý các tùy chọn của mình trên các nền tảng này.\n\n"
                          "VII.    Bảo vệ dữ liệu cá nhân\n\n"
                          "Chúng tôi sẽ thực hiện các biện pháp về mặt tổ chức, kỹ thuật và pháp lý phù hợp để bảo vệ Dữ Liệu Cá Nhân của bạn. Các biện pháp này có thể bao gồm ngăn chặn tổn thất dữ liệu, hay ngăn chặn việc sử dụng hoặc tiếp cận dữ liệu trái phép. Chúng tôi giới hạn quyền tiếp cận Dữ Liệu Cá Nhân ở nhân viên trên cơ sở cần biết. Chỉ những người được ủy quyền mới được phép xử lý Dữ Liệu Cá Nhân của bạn và thông tin của bạn sẽ được bảo mật.\n\n"
                          "Tuy nhiên, lưu ý rằng việc truyền thông tin qua Internet không hoàn toàn được bảo mật. Mặc dù chúng tôi sẽ cố gắng hết sức để bảo vệ Dữ Liệu Cá Nhân của bạn, chúng tôi không thể đảm bảo an toàn dữ liệu của bạn khi truyền qua các phương tiện trực tuyến, và do đó chúng tôi không chịu trách nhiệm về rủi ro truyền dữ liệu.\n\n"
                          "VIII.    QUYỀN CỦA BẠN ĐỐI VỚI DỮ LIỆU CÁ NHÂN\n\n"
                          "Theo luật áp dụng và quy định hiện hành, bạn có thể được quyền:\n\n"
                          "•	hỏi chúng tôi về việc xử lý Dữ Liệu Cá Nhân của bạnvà được cung cấp một bản sao Dữ Liệu Cá Nhân của bạn;\n\n"
                          "•	trong một số trường hợp, yêu cầu chỉnh sửa và/hoặc xóa Dữ Liệu Cá Nhân của bạn;\n\n"
                          "•	trong một số trường hợp, yêu cầu hạn chế hoặc phản đối việc xử lý Dữ Liệu Cá Nhân của bạn;\n\n"
                          "•	rút lại sự đồng thuận của bạn về việc xử lý Dữ Liệu Cá Nhân của bạn (khi chúng tôi đang xử lý Dữ Liệu Cá Nhân của bạn dựa trên sự đồng thuận của bạn);\n\n"
                          "•	yêu cầu nhận hoặc truyền cho một tổ chức khác, dưới dạng máy có thể đọc được, Dữ Liệu Cá Nhân mà bạn đã cung cấp cho chúng tôi khi chúng tôi đang sử dụng Dữ Liệu Cá Nhân của bạn dựa trên sự đồng thuận hoặc thực hiện một hợp đồng; và\n\n"
                          "•	khiếu nại với cơ quan chức năng giám sát có liên quan nếu quyền riêng tư của bạn bị vi phạm, hoặc nếu bạn phải chịu tổn hại do việc xử lý Dữ Liệu Cá Nhân của bạn bất hợp pháp.\n\n"
                          "Khi bạn được cung cấp tùy chọn chia sẻ Dữ Liệu Cá Nhân của bạn với chúng tôi, bạn luôn có thể chọn không làm như vậy. Nếu chúng tôi đã yêu cầu bạn đồng thuận xử lý và sau đó bạn chọn rút lại, chúng tôi sẽ tôn trọng lựa chọn đó theo nghĩa vụ pháp lý của chúng tôi. Tuy nhiên, chọn không chia sẻ Dữ Liệu Cá Nhân của bạn với chúng tôi, rút lại sự đồng thuận của bạn để chúng tôi sử dụng nó hoặc sự đồng ý của bạn với Thông Báo Bảo Mật của chúng tôi, có thể có nghĩa là chúng tôi không thể thực hiện các hành động cần thiết để đạt được mục đích xử lý được mô tả trong Phần II (Sử dụng Dữ Liệu Cá Nhân) hoặc rằng bạn không thể sử dụng Ứng Dụng hoặc Dịch vụ.\n\n"
                          "Sau khi bạn chọn rút lại sự đồng thuận của mình, chúng tôi có thể tiếp tục xử lý Dữ Liệu Cá Nhân của bạn trong phạm vi được yêu cầu hoặc theo luật khác hiện hành.\n\n"
                          "Chúng tôi sẽ sàng lọc và xác minh tất cả các yêu cầu trước. Để xác minh danh tính và/hoặc thẩm quyền thực hiện yêu cầu của bạn, chúng tôi có thể yêu cầu bạn cung cấp thông tin hoặc tài liệu hỗ trợ để chứng thực yêu cầu. Sau khi xác minh, chúng tôi sẽ xử lý các yêu cầu của bạn trong thời hạn được quy định bởi pháp luật.\n\n"
                          "\n\n"
                          "IX.    Sửa đổi và cập nhật\n\n"
                          "Alo ship 99 có thể sửa đổi, cập nhật hoặc điều chỉnh các điều khoản của Thông Báo Bảo Mật này tại bất cứ thời điểm nào. Các điều chỉnh đó sẽ được thông báo đến bạn thông qua Ứng Dụng và/ hoặc địa chỉ email đăng ký của bạn trước thời điểm có hiệu lực ít nhất năm (05) ngày làm việc.  Bạn có trách nhiệm thường xuyên kiểm tra Thông Báo Bảo Mật trên trang web. Việc tiếp tục sử dụng Ứng Dụng, s hoặc Dịch Vụ hoặc tiếp tục liên lạc hoặc tham gia với Alo ship 99 sau khi có các sửa đổi, cập nhật hoặc điều chỉnh Thông Báo Bảo Mật, bất kể là bạn đã xem xét hay chưa, sẽ tương đương với việc bạn đã chấp thuận và đồng ý đối với những sửa đổi, cập nhật hoặc điều chỉnh đó.\n\n"
                          "PHỤ LỤC 1. DỊCH VỤ ALO SHIP 99 FOR BUSINESS\n\n"
                          "I.    DIỄN GIẢI\n\n"
                          "Tất cả các điều khoản in hoa nhưng chưa được định nghĩa tại đây sẽ có cùng ý nghĩa với các điều khoản được xác định trong Điều Khoản Sử Dụng và Thông Báo Bảo Mật của Alo ship 99.\n\n"
                          "Phụ lục này là một phần của Thông Báo Bảo Mật. Trong trường hợp có bất kì mâu thuẫn nào giữa Thông Báo Bảo Mật và Phụ lục này, Phụ lục này sẽ được ưu tiên áp dụng.\n\n"
                          "II.    MỐI QUAN HỆ CỦA ALO SHIP 99 VỚI NGƯỜI DÙNG VÀ KHÁCH HÀNG\n\n"
                          "Alo ship 99 for Business hoạt động như thế nào\n\n"
                          "Alo ship 99 for Business là một dịch vụ bổ sung được cung cấp thêm vào để tạo điều kiện thanh toán qua công ty cho Người Dùng Được Cấp Quyền sử dụng dịch vụ Alo ship 99 trong quá trình làm việc.\n\n"
                          "Khi một tổ chức (“Khách Hàng Doanh Nghiệp”) chọn sử dụng dịch vụ Alo ship 99 for Business, Người Dùng Được Cấp Quyền sẽ được tùy chọn gắn thẻ hành trình của mình hoặc các giao dịch khác để phân loại giao dịch thuộc Khách Hàng Doanh Nghiệp hoặc thuộc chuyến đi cá nhân. Người Dùng Được Cấp Quyền được đề cập trong Thông Báo Bảo Mật được hiểu là hành khách. Là một phần của tính năng này, Alo ship 99 sẽ tiết lộ thông tin chi tiết về chuyến đi và thông tin đặt chỗ mà Người Dùng Được Cấp Quyền đã gắn thẻ mục đích kinh doanh vào Khách Hàng Doanh Nghiệp. Ngoại trừ cho mục đích nêu trên đó, Alo ship 99 sẽ không tiết lộ Dữ Liệu Cá Nhân khác của Người Dùng Được Cấp Quyền cho Khách Hàng Doanh Nghiệp.\n\n"
                          "Thay vào đó, một người dùng cá nhân có thể chọn thiết lập một hồ sơ doanh nghiệp trong Ứng dụng để tạo điều kiện gắn thẻ cho các chuyến đi phục vụ mục đích kinh doanh và tải báo cáo tổng hợp chuyến đi để tạo điều kiện nộp hồ sơ yêu cầu bồi hoàn từ người sử dụng lao động của mình. Khi cá nhân đó sử dụng chế độ này, quy trình yêu cầu bồi hoàn đó sẽ do chính cá nhân đó thực hiện và người sử dụng lao động của cá nhân đó không nhất thiết phải là Khách Hàng Doanh Nghiệp.\n\n"
                          "Để tiện tham khảo, trong Phụ lục này, mỗi Người Dùng Được Cấp Quyền và người dùng cá nhân sẽ được gọi riêng là “Người Dùng”, và gọi chung là “Các Người Dùng”.\n\n"
                          "Alo ship 99 là một Đơn vị Quản lý Dữ liệu, Khách hàng của chúng tôi cũng vậy\n\n"
                          "Đối với bất kỳ Người Dùng nào cũng như việc xử lý tất cả Dữ Liệu Cá Nhân của họ (bao gồm nhưng không giới hạn, Dữ liệu Liên kết và Dữ liệu Cổng thông tin), Alo ship 99 đóng vai trò là một Đơn vị Quản lý  Dữ liệu – Data Controller. Để biết thêm thông tin về cách Alo ship 99 thu thập, sử dụng và tiết lộ Dữ Liệu Cá Nhân của Người Dùng, vui lòng tham khảo Thông Báo Bảo Mật.\n\n"
                          "Do cách thức hoạt động của dịch vụ Alo ship 99 for Business, Alo ship 99 không xử lý bất kỳ Dữ Liệu Cá Nhân nào thay mặt cho Khách Hàng Doanh Nghiệp. Theo đó, Alo ship 99 không phải là một Đơn vị Xử lý Dữ liệu (Data Processor) của Khách Hàng Doanh Nghiệp, mà là một Đơn vị Quản lý Dữ liệu (Data Controller) độc lập đối với tất cả Dữ Liệu Cá Nhân mà Alo ship 99 xử lý trong quá trình cung cấp dịch vụ Alo ship 99 for Business. Tương tự, Khách Hàng Doanh Nghiệp cũng là một Đơn vị Quản lý Dữ Liệu (Data Controller) độc lập đối với Dữ Liệu Cá Nhân (ví dụ: Dữ liệu Liên kết và Dữ liệu Cổng thông tin) mà doanh nghiệp đó tiết lộ và/hoặc nhận từ Alo ship 99.\n\n"
                          "Là những đơn vị quản lý dữ liệu độc lập, Alo ship 99 và Khách Hàng Doanh nghiệp có trách nhiệm tự quyết định riêng biệt các mục đích và phương tiện xử lý Dữ Liệu Cá Nhân, tùy thuộc vào các quy định của Điều Khoản Sử Dụng và Chính Sách Bảo Mật này. Alo ship 99 và Khách Hàng Doanh Nghiệp cũng chịu trách nhiệm riêng biệt để đảm bảo bảo vệ Dữ liệu Cá nhân nằm trong phạm vi nhiệm vụ của họ.\n\n"
                          "III.    DỮ LIỆU CÁ NHÂN NÀO ĐƯỢC THU THẬP, XỬ LÝ VÀ TIẾT LỘ\n\n"
                          "Các dữ liệu Alo ship 99 thu thập như là một phần của dịch vụ Alo ship 99 for Business\n\n"
                          "Để cung cấp dịch vụ Alo ship 99 for Busniess, người dùng cá nhân hoặc Khách Hàng Doanh Nghiệp sẽ được yêu cầu cung cấp cho Alo ship 99 các thông tin sau đây về Người Dùng Được Cấp Quyền:\n\n"
                          "•	họ và tên;\n\n"
                          "•	địa chỉ email công việc; và\n\n"
                          "•	thông tin xác định khác về Người Dùng Được Cấp Quyền theo yêu cầu hợp lý từ Alo ship 99.\n\n"
                          "Alo ship 99 sẽ sử dụng thông tin này cho các mục đích:\n\n"
                          "•	xác thực Người Dùng;\n\n"
                          "•	trong trường hợp cần thiết, liên kết tài khoản Người Dùng Được Cấp Quyền với tài khoản Alo ship 99 for Business của Khách Hàng Doanh Nghiệp hoặc truy theo các chuyến xe từ hồ sơ doanh nghiệp của Người Dùng Được Cấp quyền trong Ứng dụng, tuỳ theo từng trường hợp;\n\n"
                          "•	trong trường hợp cần thiết, xác minh tình trạng thanh toán theo hình thức thanh toán doanh nghiệp của Người Dùng Được Cấp Quyền tùy theo từng thời điểm nhất định; và\n\n"
                          "•	liên hệ với Người Dùng theo các mục đích được nêu trong Thông Báo Bảo Mật.\n\n"
                          "Khi Người Dùng bắt đầu được phép sử dụng Ứng dụng, Alo ship 99 sẽ xử lý Dữ Liệu Cá Nhân của Người Dùng theo như Chính Sách Bảo Mật của Alo ship 99 và Phụ lục này.\n\n"
                          "Alo ship 99 tiết lộ gì cho Khách Hàng Doanh Nghiệp\n\n"
                          "Alo ship 99 sẽ tiết lộ thông tin về chuyến đi và các thông tin đặt xe có liên quan tùy vào quyết định của Alo ship 99 trong từng trường hợp cụ thể cho mục đích tạo điều kiện cho việc thực hiện thanh toán theo hình thức doanh nghiệp.\n\n"
                          "Alo ship 99 tiết lộ gì cho người dùng cá nhân\n\n"
                          "Tuỳ vào hồ sơ doanh nghiệp được người dùng cá nhân lựa chọn cài đặt, người dùng có thể truy xuất và tải báo cáo bao gồm thông tin các chuyến đi và cuốc xe của mình.\n\n"
                          "IV.    NGHĨA VỤ CỦA CÁC BÊN\n\n"
                          "Mỗi bên Khách hàng và Alo ship 99 sẽ:\n\n"
                          "•	riêng biệt thông báo cho Chủ thể Dữ liệu về mỗi xử lý Dữ liệu Cá nhân và cho phép Chủ thể Dữ liệu thực hiện quyền của họ theo như luật bảo vệ dữ liệu/ luật dữ liệu riêng tư của địa phương;\n\n"
                          "•	tuân thủ với nghĩa vụ tương ứng của mỗi bên theo như luật bảo vệ dữ liệu/ luật dữ liệu riêng tư áp dụng khi xử lý bất cứ Dữ liệu Cá nhân nào của Người dùng được Ủy quyền hoặc Người dùng được Đề xuất;\n\n"
                          "•	có được sự đồng thuận cần thiết (nếu có) để tạo điều kiện cung cấp tính năng Alo ship 99 for Business; và\n\n"
                          "•	thực thi các biện pháp pháp lý, kĩ thuật và tổ chức phù hợp để bảo vệ Dữ liệu Cá nhân chống lại việc xử lý trái phép hoặc bất hợp pháp và chống lại thất thoát, phá huỷ, hư hại, thay đổi hoặc tiết lộ trái phép, cũng như bất kì vi phạm hoặc cố vi phạm các biện pháp bảo mật của mỗi bên (“Sự cố An toàn Thông tin”).\n\n"
                          "PHỤ LỤC 2. TUYÊN BỐ RIÊNG TƯ CHO DỊCH VỤ ALO SHIP 99\n\n"
                          "Tuyên bố riêng tư này (“Tuyên Bố”) mô tả cách thức Công Ty Alo ship 99 Holdings Inc. và các công ty con, công ty liên kết và các tổ chức, pháp nhân cùng chịu chung sự kiểm soát (sau đây gọi chung là “Alo ship 99”, “chúng tôi”, “của chúng tôi”) thu thập, sử dụng, xử lý và tiết lộ dữ liệu thông qua việc sử dụng Alo ship 99 và các dịch vụ có liên quan khác (“Alo ship 99”).\n\n"
                          "Alo ship 99 cung cấp Alo ship 99Defence cho khách hàng của mình (“Khách Hàng GD”) để hỗ trợ ngăn chặn, phát hiện và chống lại các hoạt động gian lận hoặc không an toàn trên các nền tảng và ứng dụng của khách hàng (chẳng hạn như nền tảng thương mại điện tử dựa trên ứng dụng di động và nền tảng web) (“Nền Tảng Kỹ Thuật Số”). Khách Hàng GD sẽ tích hợp Alo ship 99Defence vào Nền Tảng Kỹ Thuật Số của mình để chủ động thu thập dữ liệu giúp xác định các hoạt động gian lận tiềm ẩn trên Nền Tảng Kỹ Thuật Số đó.\n\n"
                          "Tuyên Bố này áp dụng cho những người dùng Nền Tảng Kỹ Thuật Số của Khách Hàng GD (“bạn”) và liên quan mật thiết đến dữ liệu được thu thập, sử dụng, tiết lộ được thay mặt bởi Khách Hàng GD cho mục đích cung cấp Dịch Vụ Alo ship 99. Xin vui lòng tham khảo các điều kiện sử dụng dịch vụ hiện hành và/hoặc các thông báo bảo mật của Khách Hàng GD để hiểu được cách thức họ thu thập, sử dụng và tiết lộ dữ liệu của bạn.\n\n"
                          "Xin lưu ý rằng Alo ship 99Defence chỉ thu thập thông tin từ những người dùng Nền Tảng Kỹ Thuật Số của Khách Hàng GD, chi tiết hơn sẽ được chia sẻ thông qua Tuyên Bố này.\n\n"
                          "I.    VIỆC THU THẬP DỮ LIỆU\n\n"
                          "Để cung cấp Alo ship 99 đến Khách Hàng GD, thông tin từ thiết bị của bạn và các thông tin liên quan đến việc bạn sử dụng Nền Tảng Kỹ Thuật Số của Khách Hàng GD sẽ được thu thập. Những thông tin này sẽ bao gồm thông tin xác định thiết bị (chẳng hạn như IMEI, Android ID, địa chỉ MAC…), thông tin thiết bị và phần cứng (chẳng hạn như tên thiết bị, kích cỡ màn hình…) cũng như một số dữ liệu bối cảnh khác liên quan đến việc bạn sử dụng Nền Tảng Kỹ Thuật Số của Khách Hàng GD (chẳng hạn như địa chỉ IP, địa chỉ Wifi, dữ liệu vị trí GPS,…).\n\n"
                          "Chúng tôi có thể kết hợp thông tin mà chúng tôi đã thu thập để có được thông tin chi tiết về một thiết bị cụ thể (ví dụ, thông tin chi tiết về việc liệu có dấu hiệu sử đổi ứng dụng, thao túng thiết bị, thiết bị giả mạo, GPS giả mạo). Chúng tôi không cố gắng định danh cá nhân bạn dựa trên những thông tin trên để cung cấp Alo ship 99 cho các Khách Hàng GD.\n\n"
                          "Thông tin trên thiết bị của bạn mà chúng tôi thu thập trên đây được thực hiện khi bạn tương tác với Nền Tảng Kỹ Thuật Số của Khách Hàng GD, ví dụ, khi bạn khởi chạy Nền Tảng Kỹ Thuật Số trên thiết bị của mình hoặc khi bạn thực hiện giao dịch trên Nền Tảng Kỹ Thuật Số. Việc thu thập này sẽ được thực hiện theo các điều khoản dịch vụ và/hoặc các thông báo bảo mật của Khách Hàng GD.\n\n"
                          "II.    VIỆC SỬ DỤNG DỮ LIỆU\n\n"
                          "Chúng tôi thường xử lý thông tin của bạn thay mặt cho Khách Hàng GD để hỗ trợ họ trong nỗ lực phát hiện gian lận. Khách Hàng GD có toàn quyền quyết định việc áp dụng kết quả thu được từ việc sử dụng Alo ship 99Defence trên Nền Tảng Kỹ Thuật Số của họ.\n\n"
                          "Về vấn đề này, chúng tôi có thể sử dụng, kết hợp và xử lý thông tin của bạn cho các mục đích sau (“Mục đích”):\n\n"
                          "•	cung cấp, vận hành, duy trì Alo ship 99Defence;\n\n"
                          "•	điều tra những gian lận và khắc phục sự cố với Alo ship 99Defence;\n\n"
                          "•	nghiên cứu và phát triển Alo ship 99Defence, bao gồm nhưng không giới hạn ở việc cải thiện các tính năng và dịch vụ, hoặc việc phát triển các tính năng và dịch vụ mới cho Alo ship 99Defence;\n\n"
                          "•	phát hiện các mẫu trong tập dữ liệu được thu thập để có được thông tin chi tiết về hành vi gian lận các hoạt động;\n\n"
                          "•	các mục đích tuân thủ phát luật và kiểm soát nội bộ; và\n\n"
                          "•	phản hồi với các yêu cầu thực thi pháp luật hoặc lệnh của Tòa án.\n\n"
                          "Hãy yên tâm rằng thông tin thu thập được từ thiết bị của bạn sẽ không được Alo ship 99 sử dụng cho bất kỳ nỗ lực tiếp thị hoặc kết hợp với bất kỳ bộ dữ liệu nào mà Alo ship 99 có sẵn theo cách gây nên những bất lợi một cách không công bằng đói với bạn.\n\n"
                          "III.    VIỆC TIẾT LỘ DỮ LIỆU\n\n"
                          "Chúng tôi có thể cần chia sẻ dữ liệu với một số bên nhau cho một số Mục Đích. Những bên này bao gồm:\n\n"
                          "•	các Khách Hàng GD, người mà bạn đã đăng ký như là người dùng của họ;\n\n"
                          "•	các chi nhánh và công ty con của chúng tôi;\n\n"
                          "•	các nhà cung cấp dịch vụ của chúng tôi (ví dụ, chúng tôi sử dụng điện toán đám mây của Amazon Web Services để lưu trữ thông tin của bạn); và\n\n"
                          "•	với các cố vấn pháp lý của chúng tôi, các quan chức thực thi pháp luật, cơ quan chính phủ.\n\n"
                          "Ngoại trừ các bên đã đề cập ở trên, chúng tôi sẽ không tiết lộ thông tin của bạn cho bất kỳ bên thứ ba nào khác.\n\n"
                          "IV.    CÁC QUYỀN ĐỐI VỚI DỮ LIỆU CỦA BẠN\n\n"
                          "Phù hợp với luật hiện hành về quyền riêng tư và trong phạm vi mà bất kỳ thông tin nào được thu thập do việc sử dụng Alo ship 99 mà có thể cấu thành dữ liệu cá nhân, bạn có thể có quyền truy cập hoặc cập nhật dữ liệu cá nhân của mình. Trong trường hợp việc Alo ship 99Defence xử lý dữ liệu cá nhân của trên tiền đề việc Khách hàng GD sử dụng Alo ship 99 khi bạn sử dụng Nền Tảng Kỹ Thuật Số của họ, nếu bạn muốn thực hiện các quyền của mình, chúng tôi khuyên bạn nên liên hệ trực tiếp với người vận hành của Nền Tảng Kỹ Thuật Số mà bạn đang sử dụng để có thêm thông tin về cách thức thông tin của bạn được sử dụng và xử lý cũng như thực hiện các quyền của bạn đối với dữ liệu cá nhân của mình.\n\n"
                          "V.    VIỆC LƯU GIỮ DỮ LIỆU\n\n"
                          "Chúng tôi lưu giữ thông tin của bạn khi chúng tôi có một mục đích kinh doanh (ví dụ, để cung cấp Alo ship 99 hoặc để hoàn thành các Mục Đích) hoặc có một mục đích pháp lý để làm như vậy. Khi các mục đích đã được hoàn tất, chúng tôi sẽ thực hiện các bước để xoá, tiêu huỷ, ẩn danh thông tin của bạn.\n\n"
                          "VI.    CHUYỂN GIAO QUỐC TẾ DỮ LIỆU\n\n"
                          "Thông tin của bạn có thể được chuyển từ quốc gia, tiểu bang và thành phố (“Quốc Gia Sở Tại”), nơi bạn có mặt trong khi sử dụng Nền Tảng Kỹ Thuật Số của Khách Hàng GD đến một quốc gia, tiểu bang và thành phố khác (“Quốc Gia Thay Thế”).\n\n"
                          "VII.    BẢO VỆ DỮ LIỆU\n\n"
                          "Chúng tôi sẽ thực hiện các biện pháp về mặt tổ chức, kỹ thuật và pháp lý phù hợp để bảo vệ thông tin của bạn. Các biện pháp này có thể bao gồm ngăn chặn tổn thất dữ liệu, hay ngăn chặn việc sử dụng hoặc tiếp cận dữ liệu trái phép. Chúng tôi giới hạn quyền tiếp cận với thông tin của bạn ở nhân viên trên cơ sở cần biết. Chỉ những người được ủy quyền mới được phép xử lý dữ liệu cá nhân của bạn và thông tin của bạn sẽ được bảo mật.\n\n"
                          "Tuy nhiên, lưu ý rằng việc truyền thông tin qua Internet không hoàn toàn được bảo mật. Mặc dù chúng tôi sẽ cố gắng hết sức để bảo vệ dữ liệu cá nhân của bạn, chúng tôi không thể đảm bảo an toàn dữ liệu của bạn khi truyền qua các phương tiện trực tuyến, và do đó chúng tôi không chịu trách nhiệm về rủi ro truyền dữ liệu\n\n"
                          "VIII.    SỬA ĐỔI VÀ CẬP NHẬT\n\n"
                          "Alo ship 99 có quyền để sửa đổi, cập nhật hoặc điều chỉnh các điều khoản của Tuyên Bố này tại bất cứ thời điểm nào bằng việc đăng tải Tuyên Bố được cập nhật trên s của mình.\n\n"
                          "Nếu bạn có bất kỳ thắc mắc nào về cách thức dữ liệu bạn được sử dụng, xin vui lòng liên hệ đến Khách Hàng GD người mà bạn đã đăng ký như là người dùng của họ. Nếu bạn có bất kỳ thắc mắc nào khác liên quan đến Alo ship 99, xin vui lòng liên hệ đến các Nhân viên Bảo vệ Dữ liệu của chúng tôi qua biểu mẫu được đề cập ở Thông Báo Bảo Mật. "
                ,
                      style: AppStyle.DEFAULT_16.copyWith(),
                      textAlign: TextAlign.justify,
                    ),
                    Padding(
                      padding: EdgeInsets.only(top: 50.sp),
                      child: Image.asset(
                        'assets/icons/dieuKhoan.png',
                        width: 192.sp,
                        height: 192.sp,
                      ),
                    )
                  ],
                )),
          ),
        ],
      ),
    );
  }
}
